### PR TITLE
Restyling Toggles

### LINKED ISSUE #190: Selection toggle tweaks
Spacing, position, and colors for the selection toggles need to be fixed. Margin between them needs to be changed. 

This is the case for Swap/Liquidity as well as for slippage tolerance

See https://www.figma.com/file/Xw4IV3k3HYvTt5bYQHXdxI/Untitled?type=design&node-id=0%3A39&mode=design&t=HAdN7TehN0zUitb9-1

### PR DESCRIPTION
**Pull request by SiddharthV1**
resolves #190 . This PR is WIP

### CODE REVIEW

**Comment by gdsoumya** [comment]
WIP?

**Comment by KevinMehrabi** [comment]
@gdsoumya WIP means work in progress

**Comment by gdsoumya** [comment]
I meant to ask if this is still in wip as it's been 2 weeks since it was opened.

**Comment by SiddharthV1** [comment]
@gdsoumya  I think you missed the last few program calls, where a complete status and issues with the PR were discussed. Most of the issues got resolved but there is a pending issue of calibrating the mobile view in the absence of figma design and some of the logic for the tab component has to brought in into the slippage component. Would you like to take this issue up since your message has an implicit tone that you feel this should take less time? Meanwhile I can search for the compound code you are asking me to find for tezex. Additionally, since you have mentioned in the chat that its not possible for you to review the code without pictures i'll close this PR and create another one that combines a few issues with images for mobile and desktop

**Pull request closed without merging**
